# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd1be0b1215c71e52c6b9c2dedbc7720854d02508654a780f423dae0cd8f147f2a920bb403c045fa9bdda255341a28905b28b50a24d91a6799ce75cd9419636

test:
  secret_key_base: e806fb58993d66e38a07d2ff68c958a42316ddc36989e470639e74b6bb3ad903c22319feb25c2cf7971198fc943233fa5708026df78ac8cd47e0426e1e4d6c99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
